#!/usr/bin/env ruby
require 'open-uri'
require 'nokogiri'

# Returns the paragraphs from a Wikipedia link, stripped of reference numbers.
# Especially useful for text-to-speech (both native and foreign).
if ARGV.length == 0
  puts "This script takes one argument, which is the URL of a text document"
  exit 0
end
url = ARGV[0]
doc = Nokogiri::HTML(open(url).read)
doc.css('.reference').each(&:remove)
content_array = doc.css('p').map(&:content)
puts content_array.join("\n\n")
